# Generated by Django 3.2.1 on 2021-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db2',
            name='intgr2',
            field=models.IntegerField(choices=[(1, 'bad'), (2, 'good')], default=5),
        ),
    ]
