# Generated by Django 3.2.1 on 2021-05-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0002_db2_intgr2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db2',
            name='col2',
        ),
    ]
